const AI_ML_WORDS = [
    'AI',
    'Bard',
    'ChatGLM',
    'ChatGPT',
    'Claude 3',
    'Claude',
    'Copilot',
    'CUDA',
    'DALL-E',
    'DeepSeek',
    'Diffusion',
    'Gemini',
    'GPT-3.5',
    'GPT-3',
    'GPT-4',
    'GPT-4o',
    'GPT-4V',
    'GPT-J',
    'Hugging Face',
    'LangChain',
    'Llama 2',
    'Llama 3',
    'LLaMA',
    'LLM',
    'Midjourney',
    'NVIDIA',
    'OpenAI',
    'OpenRouter',
    'Qwen',
    'RAG',
    'Stable Diffusion',
];

const COMPANIES_BRANDS = [
    'Amazon',
    'Apple',
    'Facebook',
    'Google',
    'LinkedIn',
    'Microsoft',
    'TikTok',
    'Twitter',
    'YouTube',
    'Adobe',
    'Airbnb',
    'Alibaba',
    'Alphabet',
    'AMD',
    'Baidu',
    'ByteDance',
    'Cisco',
    'Dell',
    'Dropbox',
    'eBay',
    'Figma',
    'HP',
    'Huawei',
    'IBM',
    'Intel',
    'JetBrains',
    'Lenovo',
    'Meta',
    'Mozilla',
    'Netflix',
    'NVIDIA',
    'Oracle',
    'PayPal',
    'Qualcomm',
    'Salesforce',
    'Samsung',
    'Shopify',
    'Slack',
    'Sony',
    'Spotify',
    'Stripe',
    'Tencent',
    'Tesla',
    'Uber',
    'Xiaomi',
    'Zoom',
];

const SOFTWARE_PRODUCTS = [
    // Adobe 系列
    'Photoshop',
    'Illustrator',
    'XD',
    'InDesign',
    'Premiere Pro',
    'After Effects',
    'Lightroom',
    'Acrobat',
    'Audition',
    'Animate',
    'Dreamweaver',
    'Bridge',
    'Character Animator',
    'Dimension',
    'Media Encoder',

    // 办公软件
    'Word',
    'Excel',
    'PowerPoint',
    'Outlook',
    'Access',
    'OneNote',
    'WPS',
    'LibreOffice',
    'OpenOffice',
    'Pages',
    'Numbers',
    'Keynote',

    // 设计软件
    'Sketch',
    'Figma',
    'CorelDRAW',
    'Affinity',
    'Affinity Designer',
    'Affinity Photo',
    'Affinity Publisher',
    'Blender',
    'Maya',
    'Cinema 4D',
    'SketchUp',
    'AutoCAD',
    'Rhino',

    // 影音软件
    'VLC',
    'Windows Media Player',
    'QuickTime',
    'PotPlayer',
    'Audacity',    'Ableton Live',
    'DaVinci Resolve',
    'Final Cut Pro',
    'iMovie',
    'Vegas Pro',

    // 实用工具
    'WinRAR',
    '7-Zip',
    'TeamViewer',
    'AnyDesk',
    'CCleaner',
    'Malwarebytes',
    'Everything',
    'Snagit',
    'Camtasia',
    'OBS Studio',
    'HandBrake',
    'FileZilla',
    'Rufus',
    'Revo Uninstaller',
    'Wordpress',
]

const GAMES = [
    'Minecraft',
    'Among Us',
    'Apex Legends',
    'Call of Duty',
    'Counter-Strike',
    'CS:GO',
    'CS2',
    'Cyberpunk 2077',
    'DOTA 2',
    'Elden Ring',
    'Fortnite',
    'Genshin Impact',
    'GTA V',
    'Half-Life',
    'Honkai: Star Rail',
    'League of Legends',
    'Mario',
    'Overwatch',
    'PUBG',
    'Roblox',
    'The Legend of Zelda',
    'Valorant',
    'World of Warcraft',
]

const OPERATING_SYSTEMS = [
    'Android',
    'Arch',
    'CentOS',
    'Debian',
    'Fedora',
    'Gentoo',
    'Linux',
    'macOS',
    'openSUSE',
    'Ubuntu',
    'Windows',
    'iOS',
    'iPadOS',
    'tvOS',
    'watchOS',
    'AlmaLinux',
    'Alpine',
    'AmigaOS',
    'Chrome OS',
    'Deepin',
    'elementary OS',
    'FreeBSD',
    'HarmonyOS',
    'Kali Linux',
    'KDE Neon',
    'Kubuntu',
    'Lubuntu',
    'Manjaro',
    'MX Linux',
    'NetBSD',
    'OpenBSD',
    'Oracle Linux',
    'Pop!_OS',
    'RHEL',
    'Rocky Linux',
    'Solaris',
    'SteamOS',
    'Tails',
    'Void Linux',
    'Windows 10',
    'Windows 11',
    'Windows Server',
    'Xubuntu',
    'Zorin OS',
];

const DEV_TOOLS_EDITORS = [
    'Atom',
    'Cursor',
    'Emacs',
    'Neovim',
    'Sublime Text',
    'VS Code',
    'Vim',
    'Notepad++',
    'Android Studio',
    'AppCode',
    'Brackets',
    'CLion',
    'CodePen',
    'CodeSandbox',
    'DataGrip',
    'Eclipse',
    'Fleet',
    'GoLand',
    'IntelliJ IDEA',
    'Jupyter',
    'Komodo',
    'Light Table',
    'Nova',
    'PhpStorm',
    'PyCharm',
    'Rider',
    'RStudio',
    'RubyMine',
    'Spyder',
    'TextMate',
    'UltraEdit',
    'Visual Studio',
    'VSCodium',
    'WebStorm',
    'Xcode',
    'Zed',
];

const NOTE_KNOWLEDGE_TOOLS = [
    'Excalidraw',
    'Logseq',
    'Notion',
    'Obsidian',
    'Roam Research',
    'Trae',
    'Typora',
    'Zettlr',
    'Agenda',
    'Amplenote',
    'Anytype',
    'Athens Research',
    'Bear',
    'Capacities',
    'Craft',
    'DEVONthink',
    'Dendron',
    'Evernote',
    'Fibery',
    'Heptabase',
    'Inkdrop',
    'Joplin',
    'MarginNote',
    'Microsoft OneNote',
    'Milanote',
    'Miro',
    'Nimbus Note',
    'NotePlan',
    'Notability',
    'Notejoy',
    'Notesnook',
    'Reflect',
    'RemNote',
    'Scrintal',
    'Standard Notes',
    'Supernotes',
    'Tana',
    'TheBrain',
    'Ulysses',
    'WorkFlowy',
];

const VERSION_CONTROL = [
    'BitBucket',
    'GitHub',
    'GitLab',
    'Azure DevOps',
    'AWS CodeCommit',
    'Beanstalk',
    'Codebase',
    'Gitea',
    'Gogs',
    'Launchpad',
    'Mercurial',
    'Perforce',
    'Phabricator',
    'Plastic SCM',
    'RhodeCode',
    'SourceForge',
    'Subversion',
    'Team Foundation Server',
    'Gerrit',
    'Git',
    'SVN',
    'CVS',
];

const PROGRAMMING_LANGUAGES = [
    'CSS',
    'HTML',
    'JSON',
    'Java',
    'JavaScript',
    'LaTeX',
    'Markdown',
    'PHP',
    'Python',
    'TypeScript',
    'XML',
    'YAML',
    'Ada',
    'AppleScript',
    'Assembly',
    'Bash',
    'COBOL',
    'CoffeeScript',
    'Crystal',
    'Dart',
    'Delphi',
    'Elixir',
    'Elm',
    'Erlang',
    'Fortran',
    'Groovy',
    'Haskell',
    'Julia',
    'Kotlin',
    'Lisp',
    'Lua',
    'MATLAB',
    'Objective-C',
    'OCaml',
    'Pascal',
    'Perl',
    'PowerShell',
    'Prolog',
    'Racket',
    'Ruby',
    'Rust',
    'Scala',
    'Scheme',
    'Shell',
    'SQL',
    'Swift',
    'Tcl',
    'VB.NET',
    'Visual Basic',
    'WebAssembly',
    'WASM',
    'AsciiDoc',
    'BBCode',
    'CSV',
    'DocBook',
    'Graphviz',
    'MediaWiki',
    'reStructuredText',
    'SVG',
    'TOML',
    'TSX',
    'JSX',
];

const DEV_FRAMEWORKS_TOOLS = [
    'Angular',
    'Docker',
    'ESLint',
    'Jest',
    'Kubernetes',
    'Node.js',
    'React',
    'Vue',
    'npm',
    'webpack',
    'yarn',
    'Ansible',
    'Apollo',
    'Astro',
    'Babel',
    'Bootstrap',
    'Capacitor',
    'Composer',
    'Cordova',
    'Cypress',
    'Django',
    'Electron',
    'Ember.js',
    'Express',
    'FastAPI',
    'Flask',
    'Flutter',
    'Gatsby',
    'Git',
    'GitFlow',
    'Gradle',
    'GraphQL',
    'Gulp',
    'Helm',
    'Hugo',
    'Ionic',
    'Jenkins',
    'jQuery',
    'Laravel',
    'Lerna',
    'Lodash',
    'Maven',
    'Mocha',
    'NestJS',
    'Next.js',
    'Nginx',
    'NuGet',
    'NuxtJS',
    'Parcel',
    'Playwright',
    'Podman',
    'Prettier',
    'Prisma',
    'Prometheus',
    'Puppeteer',
    'PyPI',
    'Rails',
    'Redux',
    'Remix',
    'RollupJS',
    'RxJS',
    'Sass',
    'Selenium',
    'Sentry',
    'Serverless',
    'Spring Boot',
    'Storybook',
    'Svelte',
    'Tailwind CSS',
    'Terraform',
    'Three.js',
    'TypeORM',
    'Vite',
    'Vitest',
    'Vue Router',
    'Vuex',
    'Webpack',
    'Xamarin',
    'pnpm',
];

const DATABASES = [
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'Redis',
    'Amazon RDS',
    'Apache Cassandra',
    'Azure SQL',
    'CockroachDB',
    'Couchbase',
    'DynamoDB',
    'Elasticsearch',
    'Firebase',
    'InfluxDB',
    'MariaDB',
    'Microsoft SQL Server',
    'Neo4j',
    'Oracle Database',
    'PlanetScale',
    'RavenDB',
    'SQLite',
    'Supabase',
    'Timescale',
];

const CLOUD_SERVICES = [
    'AWS',
    'Azure',
    'Google Cloud',
    'Alibaba Cloud',
    'Cloudflare',
    'DigitalOcean',
    'Heroku',
    'IBM Cloud',
    'Linode',
    'Oracle Cloud',
    'OVHcloud',
    'Render',
    'Tencent Cloud',
    'Vercel',
    'Vultr',
];

const COMMAND_LINE_TOOLS = [
    'Bash',
    'PowerShell',
    'cmd',
    'cURL',
    'Fish',
    'Git Bash',
    'iTerm2',
    'Oh My Zsh',
    'Terminal',
    'Windows Terminal',
    'Zsh',
];

const BROWSERS = [
    'Arc',
    'Brave',
    'Chrome',
    'Edge',
    'Firefox',
    'Opera',
    'Safari',
    'Chromium',
    'DuckDuckGo',
    'Internet Explorer',
    'Tor Browser',
    'Vivaldi',
];

const MOBILE_DEVICES = [
    'iPad',
    'iPhone',
    'Android',
    'Galaxy',
    'Huawei',
    'iPad Air',
    'iPad mini',
    'iPad Pro',
    'iPhone SE',
    'Kindle',
    'Pixel',
    'Surface',
    'Xiaomi',
];

const MESSAGING_SOCIAL = [
    'Discord',
    'Instagram',
    'Slack',
    'Telegram',
    'WeChat',
    'WhatsApp',
    'BeReal',
    'Bluesky',
    'Facebook',
    'Feishu',
    'Flickr',
    'Gitter',
    'Google Chat',
    'Google Meet',
    'iMessage',
    'Kakao Talk',
    'LINE',
    'LinkedIn',
    'Mastodon',
    'Matrix',
    'Messenger',
    'Microsoft Teams',
    'Pinterest',
    'QQ',
    'Reddit',
    'Signal',
    'Skype',
    'Snapchat',
    'Threads',
    'TikTok',
    'Tumblr',
    'Twitter',
    'Viber',
    'VK',
    'WeiBo',
    'X',
    'YouTube',
    'Zoom',
];

const HARDWARE = [
    'AMD',
    'ARM',
    'AirPods',
    'Apple Watch',
    'CPU',
    'GPU',
    'HDD',
    'Intel',
    'MacBook',
    'MacBook Air',
    'MacBook Pro',
    'Mac mini',
    'Mac Pro',
    'NVIDIA',
    'RAM',
    'RTX',
    'Raspberry Pi',
    'SSD',
    'ThinkPad',
    'USB-C',
];

const PROGRAMMING_CONCEPTS = [
    'API',
    'CRUD',
    'DRY',
    'DevOps',
    'IoT',
    'MVC',
    'OOP',
    'REST',
    'SOLID',
    'TDD',
    'UI/UX',
    'WebRTC',
];

const NETWORK_PROTOCOLS = [
    'DNS',
    'FTP',
    'GraphQL',
    'HTTP',
    'HTTPS',
    'IMAP',
    'IP',
    'IPv4',
    'IPv6',
    'OAuth',
    'POP3',
    'REST',
    'SMTP',
    'SOAP',
    'SSH',
    'TCP',
    'TCP/IP',
    'UDP',
    'WebRTC',
    'WebSocket',
];

const TECH_STANDARDS = [
    'Bluetooth',
    'DisplayPort',
    'HDMI',
    'NFC',
    'USB',
    'USB-A',
    'USB-C',
    'Type-C',
    'VGA',
    'Wi-Fi',
];

const CRYPTO_BLOCKCHAIN = [
    'Bitcoin',
    'Blockchain',
    'Coinbase',
    'DAO',
    'DApp',
    'DeFi',
    'Ethereum',
    'MetaMask',
    'NFT',
    'Solana',
    'Web3',
];

// 合并所有词汇表
const CASE_SENSITIVE_WORDS = [
    ...AI_ML_WORDS,
    ...COMPANIES_BRANDS,
    ...SOFTWARE_PRODUCTS,
    ...GAMES,
    ...OPERATING_SYSTEMS,
    ...DEV_TOOLS_EDITORS,
    ...NOTE_KNOWLEDGE_TOOLS,
    ...VERSION_CONTROL,
    ...PROGRAMMING_LANGUAGES,
    ...DEV_FRAMEWORKS_TOOLS,
    ...DATABASES,
    ...CLOUD_SERVICES,
    ...COMMAND_LINE_TOOLS,
    ...BROWSERS,
    ...MOBILE_DEVICES,
    ...MESSAGING_SOCIAL,
    ...HARDWARE,
    ...PROGRAMMING_CONCEPTS,
    ...NETWORK_PROTOCOLS,
    ...TECH_STANDARDS,
    ...CRYPTO_BLOCKCHAIN,
];

/**
 * 将输入的词典数组转换为 Map 对象，用于大小写敏感词的查找
 * @param dict 包含大小写敏感词的数组
 * @returns 返回一个 Map，key 为小写词，value 为原始词
 */
const getDict = (dict) => {
    // 创建新的 Map 用于存储词典
    const dictMap = new Map();
    
    dict.forEach((word) => {
        // 将单词转换为小写作为键
        let key = word.toLowerCase();
        dictMap.set(key, word);
        
        // 如果单词包含非字母数字字符，创建一个不含特殊字符的版本作为额外的键
        if(/[- .]/.test(key)) {
            dictMap.set(key.replace(/[- .]/, ''), word);
        }
    });
    
    return dictMap;
}

// 使用默认词典初始化
const defaultDict = getDict(CASE_SENSITIVE_WORDS);

console.log(defaultDict);

/**
 * 修正文本中单词的大小写
 * @param input 需要处理的输入文本
 * @param dict 自定义词典（字符串数组或Map对象）
 * @returns 修正后的文本
 */
export const CorrectCase = (input: string, dict?: string[] | Map<string, string>) => {
    // 处理空输入
    if(!input) return '';
    // 使用提供的词典或默认词典
    dict = dict ? getDict(dict) : defaultDict;
    let result = input;
    
    // 遍历词典进行大小写修正
    for (const [key, value] of dict.entries()) {
        // 处理特殊字符
        const regexKey = key.replace(/([+.])/g, '\\$1');
        // 创建匹配整个单词的正则表达式（不区分大小写），如果是特殊字符结尾，则不匹配后面的单词边界。
        const regex = new RegExp(`\\b${regexKey}${/[+.]$/.test(regexKey) ? '' : '\\b'}`, 'gi');
        // 将匹配到的单词替换为词典中的正确形式
        result = result.replace(regex, value);
    }
    
    return result;
}